### ISSUE TITLE
苹果系统下的特殊文件是不是有影响

### ISSUE THREAD

**Issue by guohao0328** [liyinchigithub/Charles2Postman#1]
.DS_Store undefined:1 SyntaxError: Unexpected token

**Comment by liyinchigithub** [comment]
你好，确实有此bug mac 系统，文件夹会生成隐藏文件.DS_Store 造成的报错。
将在最近优化这个问题，目前只能每次执行前命令删除。。。。

**Comment by liyinchigithub** [comment]
目录下，执行
`find . -name '*.DS_Store' -type f -delete`

**Comment by liyinchigithub** [comment]
你好，已解决这个问题，试下拉取最新版本version 1.1
谢谢你的帮助哈，感恩。
