### ISSUE TITLE
转换后的文件仅有charles抓取的第一个请求

### ISSUE THREAD

**Issue by Cicy067** [liyinchigithub/Charles2Postman#11]
charles设置了仅抓取 host为xxxx的 请求，启动app抓取到大概20个请求后，导出并转换，再导入postman，仅有第一个请求。从charlea导出的文件有157KB，转换完成后的文件仅2KB。

**Comment by liyinchigithub** [comment]
@Cicy067  你好，请问有截图或者抓包文件吗？

https://github.com/liyinchigithub/Charles2Postman/issues/10
参考上面的问题试试
