### ISSUE TITLE
执行过程中遇到的问题

### ISSUE THREAD

**Issue by TonvaLi** [liyinchigithub/Charles2Postman#14]
1. 请求的本地url中包含端口号时，导出的文件中url缺少端口号；
2. 导出的文件中，存在丢失Body的情况
请问，这两个问题如何解决

**Comment by liyinchigithub** [comment]
@TonvaLi 方便提供一下抓包文件吗？我解析下看是神马场景出现的问题

**Comment by liyinchigithub** [comment]
@TonvaLi 
你好，新版1.3.3 已解决
请克隆1.3.3最新版，重新试试
https://github.com/liyinchigithub/Charles2Postman/releases/tag/v1.3.3
