### ISSUE TITLE
可以同时从charles中选择多个接口进行导出吗？

### ISSUE THREAD

**Issue by pingia** [liyinchigithub/Charles2Postman#15]
作者您好，非常感谢您的开源，我有下面这个问题，您可以抽空看下吗？
从charles中选择多个接口导出chlsj后，再运行run start命令，只会保留一个接口吗？
还是说必须每个接口都选择导出chlsj文件？

**Comment by liyinchigithub** [comment]
@pingia 您好，感谢使用，目前必须每个接口都选择导出chlsj文件；我优化下，支持一下多接口导出chlsj，感谢您的反馈

**Comment by liyinchigithub** [comment]
@pingia 多个chlsj文件目前会自动合在一个postman的collection文件中

**Comment by liyinchigithub** [comment]
@pingia 
已支持多接口单次导出，更新最新版本v1.4.0，支持同域名下多个接口导出解析

```shell
git pull git@github.com:liyinchigithub/Charles2Postman.git
```

```shell
git clone https://github.com/liyinchigithub/Charles2Postman/releases/tag/v1.4.0
```
<img width="503" alt="image" src="https://user-images.githubusercontent.com/19643260/198886779-ef327591-13fb-4339-9d16-d40b92ba8e2b.png">

<img width="803" alt="image" src="https://user-images.githubusercontent.com/19643260/198886710-b4dbf1ec-c982-4fe6-ab79-0a0127156aea.png">
