### ISSUE TITLE
Windows怎么安装呢？下载文件后执行什么？

### ISSUE THREAD

**Issue by laitaihua** [liyinchigithub/Charles2Postman#2]

**Comment by liyinchigithub** [comment]
需要先安装nodejs并配置环境变量
1.安装nodejs
https://nodejs.org/zh-cn/download/
2.nodejs环境变量配置：
https://www.jianshu.com/p/2d9fa3659645

**Comment by liyinchigithub** [comment]
1.首次使用进入目录下，执行安装依赖命令（只要执行一次）
```
npm install
```
2.将charles抓包数据，导出文件格式.chlsj放入File文件中。
3.windows双击run.bat文件，开始转换。
4.在outputFile文件中，输出支持导入postman的json文件，把这个文件导入postman。
