### ISSUE TITLE
请的参数带有端口例**.3199,导入时请求URL端口没带上 

### ISSUE THREAD

**Issue by chase001** [liyinchigithub/Charles2Postman#8]
请的参数带有端口例**：3199,导入时请求URL端口没带上

**Comment by liyinchigithub** [comment]
@chase001 
你好，新版1.3.3 已解决
请克隆1.3.3最新版，重新试试
https://github.com/liyinchigithub/Charles2Postman/releases/tag/v1.3.3

**Comment by liyinchigithub** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/19643260/179000564-cb50dbc1-3c77-4a87-93c8-feee992a81b4.png">
